import checkedIcon from '../../../img/icons/checked-icon.svg';
import editIcon from '../../../img/icons/edit-icon.svg';
import deleteIcon from '../../../img/icons/delete-grey.svg';

export default theme => ({
  title: {
    margin: '0 0 25px',
    fontSize: 24,
    fontWeight: 700,
    textAlign: 'center',
  },
  desc: {
    margin: '0 0 35px',
    fontSize: 18,
    textAlign: 'center',
    color: '#4C4C4C',
  },
  input: {
    marginBottom: 30,
  },
  chbx: {
    color: '#01c7c7',
  },
  checked: {
    color: '#01c7c7',
  },
  fieldTitle: {
    fontSize: 24,
    marginBottom: 30,
  },
  formControl: {
    width: '100%',
    marginTop: 40,
  },
  btnBox: {
    display: 'flex',
    flexWrap: 'wrap',
    justifyContent: 'flex-start',
    width: '100%',
    margin: '20px 0 0',
    textAlign: 'center',
  },
  linkBtn: {
    padding: '10px 15px',
    margin: '0 20px 20px 0',
    color: '#FFFFFF',
    border: '2px solid #00c7c7',
    backgroundColor: '#00c7c7',
    fontSize: 18,
    lineHeight: 1.2,
    borderRadius: 5,
    transition: `all 0.2s`,
  },
  continueBtnBox: {
    margin: '40px 0 0',
    textAlign: 'center',
  },
  continueLinkBtn: {
    ...theme.linkActions.linkBtn(theme.transitions.easing.easeOut, theme.palette.BLColors.main),
    textTransform: 'none',
    '@media (max-width: 1023px)': {
      width: '100%',
      maxWidth: 700,
      height: 70,
      fontSize: 24,
    },
    '@media (min-width: 1024px)': {
      padding: '0 50px',
      fontSize: 18,
    },
  },
  cleanBtn: {
    padding: '10px 15px',
    margin: '0 20px 20px 0',
    border: '2px solid #4C4C4C',
    fontSize: 18,
    lineHeight: 1.2,
    color: '#4C4C4C',
    backgroundColor: '#FFFFFF',
    borderRadius: 5,
    transition: `all 0.2s`,
    '&:hover': {
      color: '#00c7c7',
      borderColor: '#00c7c7',
    },
  },
  searchBox: {
    display: 'flex',
    maxWidth: 700,
    margin: '40px auto 40px 0',
    '& > div': {
      flexGrow: 1,
    },
  },
  searchBtn: {
    height: 40,
    width: 40,
    marginRight: 21,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    boxShadow: '0px 2px 10px rgba(0, 0, 0, 0.15)',
    borderRadius: 5,
  },
  searchAutocomplete: {
    paddingTop: 5,
  },
  searchInput: {
    height: 40,
    width: '100%',
    maxWidth: 400,
    padding: '0 12px',
    border: 'none',
    boxShadow: '0px 2px 10px rgba(0, 0, 0, 0.15)',
    borderRadius: 5,
    fontSize: 14,
  },
  serviceBox: {
    display: 'flex',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    alignItems: 'center',
    maxWidth: 700,
    margin: '40px auto',
    padding: '11px 15px 11px 25px',
    boxShadow: '0px 2px 10px rgba(0, 0, 0, 0.15)',
    borderRadius: 5,
  },
  serviceTitle: {
    margin: '0 auto 0 0',
    fontWeight: 700,
    fontSize: 18,
    lineHeight: '22px',
    color: '#C4C4C4',
  },
  checkedIcon: {
    height: 18,
    width: 20,
    marginRight: 10,
    display: 'inline-block',
    background: `url("${checkedIcon}") 50% 0/100% no-repeat`,
    cursor: 'pointer',
  },
  editBtn: {
    height: 16,
    width: 16,
    marginRight: 10,
    display: 'inline-block',
    background: `url("${editIcon}") 50% 0/100% no-repeat`,
    cursor: 'pointer',
    border: 'transparent',
  },
  deleteBtn: {
    height: 32,
    width: 32,
    display: 'inline-block',
    background: `url("${deleteIcon}") 50% 50%/50% no-repeat`,
    cursor: 'pointer',
    border: 'transparent',
  },
  servicePrice: {
    fontSize: 14,
    lineHeight: '22px',
    color: '#4C4C4C',
    '@media (max-width: 479px)': {
      order: 2,
      width: '100%',
    },
    '@media (min-width: 480px)': {
      marginRight: 20,
      marginLeft: 'auto',
    },
  },
  addBtn: {
    position: 'relative',
    height: 32,
    width: 32,
    borderRadius: '50%',
    border: '1px solid #C4C4C4',
    '&:before': {
      position: 'absolute',
      zIndex: 1,
      top: 15,
      left: 7,
      width: 18,
      height: 1,
      backgroundColor: '#C4C4C4',
      display: 'block',
      content: '""',
    },
    '&:after': {
      position: 'absolute',
      zIndex: 1,
      top: 7,
      left: 15,
      width: 1,
      height: 18,
      backgroundColor: '#C4C4C4',
      display: 'block',
      content: '""',
    },
  },
  serviceCont: {
    width: '100%',
    padding: '25px 0 0',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexWrap: 'wrap',
  },
  priceTitle: {
    position: 'relative',
    margin: '0 32px 0 0',
    fontSize: 18,
    color: '#4C4C4C',
    minWidth: 160,
    '&:after': {
      position: 'absolute',
      zIndex: 1,
      top: -4,
      right: -32,
      width: 1,
      height: 30,
      backgroundColor: '#C4C4C4',
      display: 'block',
      content: '""',
    },
  },
  priceInput: {
    maxWidth: 100,
    marginLeft: 32,
    fontSize: 18,
    fontWeight: 700,
    color: '#4C4C4C',
    borderColor: 'transparent',
    borderBottom: '1px solid #4C4C4C',
  },
});
