/*
 *
 * MasterPage constants
 *
 */

export const GET_MASTER_INFO_BY_ID = 'app/MasterPage/GET_MASTER_INFO_BY_ID';
export const GET_MASTER_INFO_BY_ID_SUCCESS = 'app/MasterPage/GET_MASTER_INFO_BY_ID_SUCCESS';
export const GET_MASTER_INFO_BY_ID_FAIL = 'app/MasterPage/GET_MASTER_INFO_BY_ID_FAIL';

export const GET_MASTER_SUB_SERVICES = 'app/MasterPage/GET_MASTER_SUB_SERVICES';
export const GET_MASTER_SUB_SERVICES_SUCCESS = 'app/MasterPage/GET_MASTER_SUB_SERVICES_SUCCESS';
export const GET_MASTER_SUB_SERVICES_FAIL = 'app/MasterPage/GET_MASTER_SUB_SERVICES_FAIL';

export const GET_MASTER_RATING_AND_REVIEW = 'app/MasterPage/GET_MASTER_RATING_AND_REVIEW';
export const GET_MASTER_RATING_AND_REVIEW_SUCCESS = 'app/MasterPage/GET_MASTER_RATING_AND_REVIEW_SUCCESS';
export const GET_MASTER_RATING_AND_REVIEW_FAIL = 'app/MasterPage/GET_MASTER_RATING_AND_REVIEW_FAIL';

export const POST_FAVORITE_MASTER = 'app/MasterPage/POST_FAVORITE_MASTER';
export const POST_FAVORITE_MASTER_SUCCESS = 'app/MasterPage/POST_FAVORITE_MASTER_SUCCESS';
export const POST_FAVORITE_MASTER_FAIL = 'app/MasterPage/POST_FAVORITE_MASTER_FAIL';
