/*
 *
 * Checkout constants
 *
 */

export const GET_BOOKING = 'app/Checkout/GET_BOOKING';
export const GET_BOOKING_SUCCESS = 'app/Checkout/GET_BOOKING_SUCCESS';
export const GET_BOOKING_FAIL = 'app/Checkout/GET_BOOKING_FAIL';

export const GET_PAYMENT_PROCESSING = 'app/Checkout/GET_PAYMENT_PROCESSING';
export const GET_PAYMENT_PROCESSING_SUCCESS = 'app/Checkout/GET_PAYMENT_PROCESSING_SUCCESS';
export const GET_PAYMENT_PROCESSING_FAIL = 'app/Checkout/GET_PAYMENT_PROCESSING_FAIL';

export const PUT_BOOKING_CUSTOMER_CANCEL = 'app/Checkout/PUT_BOOKING_CUSTOMER_CANCEL';
export const PUT_BOOKING_CUSTOMER_CANCEL_SUCCESS = 'app/Checkout/PUT_BOOKING_CUSTOMER_CANCEL_SUCCESS';
export const PUT_BOOKING_CUSTOMER_CANCEL_FAIL = 'app/Checkout/PUT_BOOKING_CUSTOMER_CANCEL_FAIL';
